"""
Gemini Integration - Collaborative AI building with Google Gemini

Enables Copilot and Gemini to work together on code generation,
review, and iterative improvement.
"""

import os
import logging
from pathlib import Path
from typing import Optional, Dict, Any
import json

logger = logging.getLogger(__name__)

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False
    logger.warning("google-generativeai not installed. Install with: pip install google-generativeai")


class GeminiCollaborator:
    """
    Gemini API integration for collaborative code generation.
    
    Usage:
        collaborator = GeminiCollaborator(api_key="your-key")
        code = collaborator.generate_code("Create a FastAPI endpoint for model inference")
        review = collaborator.review_code(code, "Check for security issues")
    """
    
    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.0-flash-exp"):
        """
        Initialize Gemini collaborator.
        
        Args:
            api_key: Gemini API key (or set GEMINI_API_KEY env var)
            model_name: Model to use (default: gemini-2.0-flash-exp)
        """
        if not GEMINI_AVAILABLE:
            raise ImportError(
                "google-generativeai not installed. "
                "Install with: pip install google-generativeai"
            )
        
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "Gemini API key required. Set GEMINI_API_KEY environment variable "
                "or pass api_key parameter"
            )
        
        genai.configure(api_key=self.api_key)
        self.model = genai.GenerativeModel(model_name)
        self.model_name = model_name
        logger.info(f"Gemini collaborator initialized with model: {model_name}")
    
    def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate code using Gemini.
        
        Args:
            prompt: Description of what code to generate
            language: Programming language (default: python)
            context: Additional context (file contents, dependencies, etc.)
        
        Returns:
            Generated code as string
        """
        full_prompt = self._build_code_prompt(prompt, language, context)
        
        try:
            response = self.model.generate_content(full_prompt)
            code = self._extract_code(response.text)
            logger.info(f"Generated {len(code)} chars of {language} code")
            return code
        except Exception as e:
            logger.error(f"Code generation failed: {e}")
            raise
    
    def review_code(
        self,
        code: str,
        focus: str = "general",
        style_guide: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Review code using Gemini.
        
        Args:
            code: Code to review
            focus: Review focus (security, performance, style, general)
            style_guide: Optional style guide to follow
        
        Returns:
            Dict with review results (issues, suggestions, score)
        """
        prompt = self._build_review_prompt(code, focus, style_guide)
        
        try:
            response = self.model.generate_content(prompt)
            review = self._parse_review(response.text)
            logger.info(f"Code review completed with {len(review.get('issues', []))} issues")
            return review
        except Exception as e:
            logger.error(f"Code review failed: {e}")
            raise
    
    def iterate_with_copilot(
        self,
        copilot_output: str,
        improvement_request: str
    ) -> str:
        """
        Take Copilot-generated code and iterate on it with Gemini.
        
        Args:
            copilot_output: Code generated by Copilot
            improvement_request: What to improve
        
        Returns:
            Improved code
        """
        prompt = f"""
You are collaborating with GitHub Copilot on the Mythos Glasseye project.

Copilot generated this code:
```python
{copilot_output}
```

Improvement request: {improvement_request}

Please provide an improved version of the code that addresses the request.
Keep the same structure and intent, but improve as requested.

Return only the improved code without explanations.
"""
        
        try:
            response = self.model.generate_content(prompt)
            improved_code = self._extract_code(response.text)
            logger.info("Code iteration completed")
            return improved_code
        except Exception as e:
            logger.error(f"Code iteration failed: {e}")
            raise
    
    def _build_code_prompt(
        self,
        prompt: str,
        language: str,
        context: Optional[Dict[str, Any]]
    ) -> str:
        """Build prompt for code generation"""
        base_prompt = f"""
You are a code generation assistant for the Mythos Glasseye project.

Task: {prompt}
Language: {language}

Requirements:
- Follow PEP 8 for Python code
- Include type hints
- Add docstrings for classes and functions
- Handle errors appropriately
- Keep code modular and testable

"""
        
        if context:
            base_prompt += "\nContext:\n"
            for key, value in context.items():
                base_prompt += f"- {key}: {value}\n"
        
        base_prompt += "\nGenerate clean, production-ready code. Return only the code without explanations."
        
        return base_prompt
    
    def _build_review_prompt(
        self,
        code: str,
        focus: str,
        style_guide: Optional[str]
    ) -> str:
        """Build prompt for code review"""
        prompt = f"""
You are a code reviewer for the Mythos Glasseye project.

Review the following code with focus on: {focus}

Code:
```python
{code}
```

"""
        
        if style_guide:
            prompt += f"\nStyle Guide: {style_guide}\n"
        
        prompt += """
Provide a structured review in JSON format:
{
  "score": 0-10,
  "issues": [
    {"severity": "high|medium|low", "line": 123, "description": "..."}
  ],
  "suggestions": ["..."],
  "summary": "Overall assessment"
}

Focus on:
- Security vulnerabilities
- Performance issues
- Code quality and maintainability
- Best practices
"""
        
        return prompt
    
    def _extract_code(self, response: str) -> str:
        """Extract code from markdown code blocks"""
        # Remove markdown code blocks
        lines = response.split("\n")
        code_lines = []
        in_code_block = False
        
        for line in lines:
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                continue
            if in_code_block or (not line.strip().startswith("#") and line.strip()):
                code_lines.append(line)
        
        return "\n".join(code_lines).strip()
    
    def _parse_review(self, response: str) -> Dict[str, Any]:
        """Parse review response"""
        try:
            # Try to parse JSON response
            json_start = response.find("{")
            json_end = response.rfind("}") + 1
            if json_start >= 0 and json_end > json_start:
                review_data = json.loads(response[json_start:json_end])
                return review_data
        except json.JSONDecodeError:
            pass
        
        # Fallback: return raw response
        return {
            "score": 0,
            "issues": [],
            "suggestions": [],
            "summary": response
        }


# Example usage
if __name__ == "__main__":
    # Example: Generate a new agent
    collaborator = GeminiCollaborator()
    
    new_agent_code = collaborator.generate_code(
        prompt="Create a CLIHelperAgent that generates user-friendly CLI commands",
        language="python",
        context={
            "base_class": "BaseAgent from mythos_glasseye.agents.base",
            "purpose": "Auto-generate CLI wrappers for glasseye build/train/serve commands"
        }
    )
    
    print("Generated Code:")
    print(new_agent_code)
    
    # Review the code
    review = collaborator.review_code(new_agent_code, focus="security")
    print(f"\nReview Score: {review['score']}/10")
    print(f"Issues: {len(review.get('issues', []))}")
